<a href="https://colab.research.google.com/github/Praneethgajula01/aml-0026/blob/main/pandas_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
"""
1. Create a Pandas Series containing the marks: 78, 85, 92, 67, 88

    Display:

	Complete Series
	Values
	Index
	Data type
	Mean
	Maximum
	Minimum
"""

import pandas as pd

marks=pd.Series([78, 85, 92, 67, 88])
print(marks)
print(marks.values)
print(marks.index)
print(marks.dtype)

0    78
1    85
2    92
3    67
4    88
dtype: int64
[78 85 92 67 88]
RangeIndex(start=0, stop=5, step=1)
int64

In [2]:
"""
Create a Series containing:

   	| Student | Marks |
	| ------- | ----: |
	| Asha    |    85 |
	| Ravi    |    78 |
	| Meena   |    92 |
	| Kiran   |    74 |
	| Arun    |    88 |
	Display the marks of Meena.
"""


marks=pd.Series({'Asha':85, 'Ravi':78, 'Meena':92, 'Kiran':74, 'Arun':88})
print(marks)
print(marks['Meena'])

Asha     85
Ravi     78
Meena    92
Kiran    74
Arun     88
dtype: int64
92

In [3]:
"""
Create the following DataFrame:

| Name  | Age | Department | Marks |
| ----- | --: | ---------- | ----: |
| Asha  |  22 | CSE        |    85 |
| Ravi  |  23 | ECE        |    78 |
| Meena |  21 | CSE        |    92 |
| Kiran |  24 | ME         |    74 |
| Arun  |  22 | ECE        |    88 |

Display:

	Complete DataFrame
	First 3 rows
	Last 2 rows
	Shape
	Column names
	Data types
"""


df=pd.DataFrame({'Name':['Asha', 'Ravi', 'Meena', 'Kiran', 'Arun'],
                 'Age':[22, 23, 21, 24, 22],
                 'Department':['CSE', 'ECE', 'CSE', 'ME', 'ECE'],
                 'Marks':[85, 78, 92, 74, 88]})
print(df)

print(df[:3])

print(df[-2:])

print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.info())
print(df.describe())

    Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
3  Kiran   24         ME     74
4   Arun   22        ECE     88
    Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
    Name  Age Department  Marks
3  Kiran   24         ME     74
4   Arun   22        ECE     88
(5, 4)
Index(['Name', 'Age', 'Department', 'Marks'], dtype='object')
Name          object
Age            int64
Department    object
Marks          int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         5 non-null      int64
 2   Department  5 non-null      object
 3   Marks       5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes
None
             Age      Marks
count   5.000000   5.000000
mean   22.400000  83.400000
std     1.140175   7.334848
min    21.000000  74.000000
25%    22.000000  78.000000
50%    22.000000  85.000000
75%    23.000000  88.000000
max    24.000000  92.000000

In [4]:
"""
Using the previous DataFrame, display:

	info()
	describe()
	Number of rows
	Number of columns
"""



print(df.info())
print(df.describe())
print(df.shape[0])
print(df.shape[1])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         5 non-null      int64
 2   Department  5 non-null      object
 3   Marks       5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes
None
             Age      Marks
count   5.000000   5.000000
mean   22.400000  83.400000
std     1.140175   7.334848
min    21.000000  74.000000
25%    22.000000  78.000000
50%    22.000000  85.000000
75%    23.000000  88.000000
max    24.000000  92.000000
5
4

In [5]:
"""
Using df, display:

	Name column
	Marks column
	Name and Marks together
"""

print(df["Name"])
print(df["Marks"])
print(df[["Name", "Marks"]])

0     Asha
1     Ravi
2    Meena
3    Kiran
4     Arun
Name: Name, dtype: object
0    85
1    78
2    92
3    74
4    88
Name: Marks, dtype: int64
    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3  Kiran     74
4   Arun     88

In [6]:
"""
 Display:

	First row using iloc
	Third row using iloc
	Rows 1 to 3
	Name and Marks columns using loc
"""

print(df.iloc[0])
print(df.iloc[2])

print(df.iloc[:3])

print(df.loc[:, ['Name', 'Marks']])

Name          Asha
Age             22
Department     CSE
Marks           85
Name: 0, dtype: object
Name          Meena
Age              21
Department      CSE
Marks            92
Name: 2, dtype: object
    Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3  Kiran     74
4   Arun     88

In [7]:
"""
Find:

	Students scoring above 80.
	Students scoring between 75 and 90.
	Students belonging to CSE.
	CSE students scoring above 80.
"""

print(df[df["Marks"]>80])
print(df[(df["Marks"]>75) & (df["Marks"]<90)])


cse_df=df[df["Department"]=="CSE"]
print(cse_df)
print(cse_df[cse_df["Marks"]>80])

    Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92
4   Arun   22        ECE     88
   Name  Age Department  Marks
0  Asha   22        CSE     85
1  Ravi   23        ECE     78
4  Arun   22        ECE     88
    Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92
    Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92

In [8]:
#Display students belonging to either CSE or ECE.

print(df[(df["Department"]=="CSE") | (df["Department"]=="ECE")])

    Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
4   Arun   22        ECE     88

In [9]:
#9. Add a new column called Result. Students scoring 75 or above should receive "Pass", otherwise "Fail".

df["Result"]=["Pass" if marks>=75 else "Fail" for marks in df["Marks"]]

df

    Name  Age Department  Marks Result
0   Asha   22        CSE     85   Pass
1   Ravi   23        ECE     78   Pass
2  Meena   21        CSE     92   Pass
3  Kiran   24         ME     74   Fail
4   Arun   22        ECE     88   Pass

In [10]:
"""
10. Assign grades according to:

	| Marks | Grade |
	| ----: | ----- |
	|  ≥ 90 | A     |
	|  ≥ 80 | B     |
	|  ≥ 70 | C     |
	|  < 70 | D     |
"""

df["Grade"] = ["A" if marks >= 90 else "B" if marks >= 80 else "C" if marks >= 70 else "D" for marks in df["Marks"]]

df

    Name  Age Department  Marks Result Grade
0   Asha   22        CSE     85   Pass     B
1   Ravi   23        ECE     78   Pass     C
2  Meena   21        CSE     92   Pass     A
3  Kiran   24         ME     74   Fail     C
4   Arun   22        ECE     88   Pass     B

In [11]:
"""
Sort students:

	By marks in ascending order.
	By marks in descending order.
	By Department and then Marks.
"""

print(df.sort_values(by="Marks"))
print(df.sort_values(by="Marks", ascending=False))
print(df.sort_values(by=["Department", "Marks"]))

    Name  Age Department  Marks Result Grade
3  Kiran   24         ME     74   Fail     C
1   Ravi   23        ECE     78   Pass     C
0   Asha   22        CSE     85   Pass     B
4   Arun   22        ECE     88   Pass     B
2  Meena   21        CSE     92   Pass     A
    Name  Age Department  Marks Result Grade
2  Meena   21        CSE     92   Pass     A
4   Arun   22        ECE     88   Pass     B
0   Asha   22        CSE     85   Pass     B
1   Ravi   23        ECE     78   Pass     C
3  Kiran   24         ME     74   Fail     C
    Name  Age Department  Marks Result Grade
0   Asha   22        CSE     85   Pass     B
2  Meena   21        CSE     92   Pass     A
1   Ravi   23        ECE     78   Pass     C
4   Arun   22        ECE     88   Pass     B
3  Kiran   24         ME     74   Fail     C

In [12]:
"""
Consider:

data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, np.nan, 24, 22],
    "Marks": [85, np.nan, 92, 74, 88]
}

"""
import numpy as np

data= {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, np.nan, 24, 22],
    "Marks": [85, np.nan, 92, 74, 88]
}

students=pd.DataFrame(data)

print(students.notna())

print("no of missing values in each value:")

for col in data:
    print(f"{col}: {students[col].isna().sum()}")

print("rows containing missing values:")
print(students.isna().sum(axis=1))
print(students.isna().any(axis=1))

   Name    Age  Marks
0  True   True   True
1  True   True  False
2  True  False   True
3  True   True   True
4  True   True   True
no of missing values in each value:
Name: 0
Age: 1
Marks: 1
rows containing missing values:
0    0
1    1
2    1
3    0
4    0
dtype: int64
0    False
1     True
2     True
3    False
4    False
dtype: bool

In [13]:
"""
13. Replace:

	Missing Age with average Age
	Missing Marks with average Marks
"""

students["Age"].fillna(students["Age"].mean())
students["Marks"].fillna(students["Marks"].mean())
print(students)

    Name   Age  Marks
0   Asha  22.0   85.0
1   Ravi  23.0    NaN
2  Meena   NaN   92.0
3  Kiran  24.0   74.0
4   Arun  22.0   88.0

In [14]:
"""
14. Remove rows containing missing values.

"""

print(students.dropna())

    Name   Age  Marks
0   Asha  22.0   85.0
3  Kiran  24.0   74.0
4   Arun  22.0   88.0

In [15]:
"""
15. Consider:

data = {
    "Name": ["Asha", "Ravi", "Meena", "Asha", "Arun"],
    "Marks": [85, 78, 92, 85, 88]
}
"""
data = {
    "Name": ["Asha", "Ravi", "Meena", "Asha", "Arun"],
    "Marks": [85, 78, 92, 85, 88]
}
df2 = pd.DataFrame(data)

print(df2.duplicated())
print(" ")
print(df2[df2.duplicated()])

print("--- ")
df2=df2.drop_duplicates()
print(df2)
print("-- ")
print(df2.iloc[3])

#print(df2)

0    False
1    False
2    False
3     True
4    False
dtype: bool

   Name  Marks
3  Asha     85
---
    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
4   Arun     88
--
Name     Arun
Marks      88
Name: 4, dtype: object

In [16]:
"""
16. Given:

marks = pd.DataFrame({
    "Student": ["A", "B", "C", "D", "E"],
    "Marks": [78, 85, 92, 67, 88]
})

Calculate:

Mean
Median
Maximum
Minimum
Standard deviation
Sum
"""

marks=pd.DataFrame({
    "Student": ["A", "B", "C", "D", "E"],
    "Marks": [78, 85, 92, 67, 88]
})

print("Mean:", marks["Marks"].mean())
print("Median:", marks["Marks"].median())
print("Max:", marks["Marks"].max())
print("Min:", marks["Marks"].min())
print("std:", int(marks["Marks"].std()))
print("sum:", marks["Marks"].sum())

Mean: 82.0
Median: 85.0
Max: 92
Min: 67
std: 9
sum: 410

In [17]:
"""
17. Consider:

data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE"
    ],

    "Marks": [
        85, 78, 92,
        74, 88, 80
    ]
}

df = pd.DataFrame(data)


Find:
Average marks by department
Maximum marks by department
Number of students in each department

For each department, calculate:
Mean
Minimum
Maximum
Count
"""

data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE"
    ],

    "Marks": [
        85, 78, 92,
        74, 88, 80
    ]
}

df=pd.DataFrame(data)
print(df.groupby("Department")["Marks"].mean())
print(df.groupby("Department")["Marks"].max())
print(df.groupby("Department")["Marks"].count())

#by using agg function

print(df.groupby("Department")["Marks"].agg(["mean", "min", "max", "count"]))

Department
CSE    85.666667
ECE    83.000000
ME     74.000000
Name: Marks, dtype: float64
Department
CSE    92
ECE    88
ME     74
Name: Marks, dtype: int64
Department
CSE    3
ECE    2
ME     1
Name: Marks, dtype: int64
                 mean  min  max  count
Department
CSE         85.666667   80   92      3
ECE         83.000000   78   88      2
ME          74.000000   74   74      1

In [18]:
"""
Create:

students = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Name": ["Asha", "Ravi", "Meena", "Kiran"]
})

marks = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Marks": [85, 78, 92, 74]
})

Combine both DataFrames using StudentID.


"""

students = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Name": ["Asha", "Ravi", "Meena", "Kiran"]
})

marks=pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Marks": [85, 78, 92, 74]
})



combined_dataframe=pd.merge(students, marks, on="StudentID")

combined_dataframe

   StudentID   Name  Marks
0        101   Asha     85
1        102   Ravi     78
2        103  Meena     92
3        104  Kiran     74

In [19]:
import numpy as np

data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya",
        "John", "Priya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE",
        "ME", "ECE"
    ],

    "Attendance": [
        92, 75, 96, 68,
        82, 88, 72, 95
    ],

    "Internal": [
        85, 72, 94, 65,
        80, 86, 70, 91
    ],

    "FinalMarks": [
        88, 74, 96, 62,
        83, 89, 68, 93
    ]
}

df = pd.DataFrame(data)

df

#first five

print(df[0:5])
print(df.ndim)

#Find the average final mark.
print(df.FinalMarks.mean().astype(int))

#Find the highest-scoring student.
print(df.FinalMarks.max())

#Find the highest-scoring student.
print(df.FinalMarks.min())

#students scoring above 80
print(df[df.FinalMarks>80])

#Find average marks by department.
print(df.groupby("Department")["FinalMarks"].mean())

#students with attendance above 80%
print(df[df["Attendance"]>80])

#sort students by final marks
print(df.sort_values(by="FinalMarks"))

#result column for pass or fail
df["Result"]=["pass" if marks>=80 else "fail" for marks in df["FinalMarks"]]
df

# performance category

conditions=[ df["FinalMarks"]>=90, df["FinalMarks"]>=80, df["FinalMarks"]>=70]
category=["Excellent", "Very Good", "Good"]


df["Performance"]=np.select(conditions, category, default="Needs improvement")

df


#dept having highest avg final marks
print(df.groupby("Department")["FinalMarks"].mean())
print(df.groupby("Department")["FinalMarks"].mean().idxmax())

    Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
1   Ravi        ECE          75        72          74
2  Meena        CSE          96        94          96
3  Kiran         ME          68        65          62
4   Arun        ECE          82        80          83
2
81
96
62
    Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
2  Meena        CSE          96        94          96
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93
Department
CSE    91.000000
ECE    83.333333
ME     65.000000
Name: FinalMarks, dtype: float64
    Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
2  Meena        CSE          96        94          96
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93
    Name Department  Attendance  Internal  FinalMarks
3  Kiran         ME          68        65          62
6   John         ME          72        70          68
1   Ravi        ECE          75        72          74
4   Arun        ECE          82        80          83
0   Asha        CSE          92        85          88
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93
2  Meena        CSE          96        94          96
Department
CSE    91.000000
ECE    83.333333
ME     65.000000
Name: FinalMarks, dtype: float64
CSE

In [20]:
"""
employees = pd.DataFrame({
    "Employee": [
        "E01", "E02", "E03", "E04",
        "E05", "E06", "E07", "E08"
    ],

    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "Finance", "IT", "Finance"
    ],

    "Experience": [
        5, 3, 7, 4,
        6, 8, 2, 5
    ],

    "Salary": [
        60000, 45000, 75000, 65000,
        55000, 85000, 48000, 70000
    ]
})
"""

employees = pd.DataFrame({
    "Employee": [
        "E01", "E02", "E03", "E04",
        "E05", "E06", "E07", "E08"
    ],

    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "Finance", "IT", "Finance"
    ],

    "Experience": [
        5, 3, 7, 4,
        6, 8, 2, 5
    ],

    "Salary": [
        60000, 45000, 75000, 65000,
        55000, 85000, 48000, 70000
    ]
})

print(employees["Salary"].mean())

#max and min salary
print(employees["Salary"].min())
print(employees["Salary"].max())


#Employee receiving the highest salary.
print(employees[employees["Salary"]==employees["Salary"].max()])

#above 60k

print(employees[employees["Salary"]>60000])

#avg salary for each dept
print(employees.groupby("Department")["Salary"].mean().round(2))

#avg exp
print(employees.groupby("Department")["Experience"].mean().round(2))

#no of emp in each dept
print(employees.groupby("Department")["Employee"].count())

#sort employees by salary

print(employees.sort_values(by="Salary", ascending=False))


#Find IT employees with more than 3 years of experience.
print(employees[(employees["Department"]=="IT") & (employees["Experience"]>3)])

62875.0
45000
85000
  Employee Department  Experience  Salary
5      E06    Finance           8   85000
  Employee Department  Experience  Salary
2      E03         IT           7   75000
3      E04    Finance           4   65000
5      E06    Finance           8   85000
7      E08    Finance           5   70000
Department
Finance    73333.33
HR         50000.00
IT         61000.00
Name: Salary, dtype: float64
Department
Finance    5.67
HR         4.50
IT         4.67
Name: Experience, dtype: float64
Department
Finance    3
HR         2
IT         3
Name: Employee, dtype: int64
  Employee Department  Experience  Salary
5      E06    Finance           8   85000
2      E03         IT           7   75000
7      E08    Finance           5   70000
3      E04    Finance           4   65000
0      E01         IT           5   60000
4      E05         HR           6   55000
6      E07         IT           2   48000
1      E02         HR           3   45000
  Employee Department  Experience  Salary
0      E01         IT           5   60000
2      E03         IT           7   75000